homepage/models.py, patients/models.py, patients/tests.py
removed naive datetime warnings by converting all relevant fields to timezone.now using django.utils.timezone
=> changed all datetime objects to timezone objects

homepage/models.py, homepage/tests_views.py, homepage/views.py
django users automatically have their username downcased on creation and save, login route modified to reflect this for case insensitive login
=> Case insensitive username

procedures/forms.py, procedures/models.py, procedures/templates/new_procedure.html, procedures/templates/procedure_main.html, procedures/templates/update_procedure.html, procedures/templates/view_procedure.html, procedures/tests_forms.py, procedures/tests_models.py, procedures/tests_views.py, procedures/urls.py, procedures/views.py
Users can now see all procedures created on the system as well as look at, update, and delete each one individually.
=> View procedure

patients/models.py, patients/tests_models.py, procedures/models.py
Code coverage is at 95% after adding test to patient model. Reverted from foreign key idea to simple character field for procedure. Added comment to procedures for Roadmap implementation next Sprint. 
All Tests Pass.
=> Proc and pat

homepage/templates/global_js.html, homepage/templates/global_styles.html, homepage/templates/homepage.html, homepage/templates/sidebar.html, homepage/tests_views.py, homepage/views.py, patients/templates/landing_page.html, patients/templates/new_patient.html, patients/templates/patient.html, patients/templates/update_patient.html, patients/tests_views.py, patients/views.py, procedures/templates/new_procedure.html, procedures/templates/procedure_main.html, procedures/templates/update_procedure.html, procedures/templates/view_procedure.html, procedures/tests_views.py, procedures/views.py
Some tests in the project were using assertTrue when assertEqual was the intended assertion. Also the <title> of the page is defined by the context returned in each views.py method.
=> Minor Fix to Tests & Restructure HTML

homepage/static/homepage/homepage.css, homepage/static/homepage/homepage.js, homepage/static/homepage/sidebar.css, homepage/templates/homepage.html, homepage/views.py
Patient panels now exist on the homepage. They're currently being labeled (i.e "Referred", "In-Progress", "Ready", "Done" , "TAVR", etc.)without a connection to any models, but can be easily connected when those features are ready. A user can also sort the list by first or last name, and choose to display patients who are in select steps of the process.
=> Patient panels

patients/forms.py, patients/models.py, patients/templates/landing_page.html, patients/tests_views.py, patients/views.py, procedures/forms.py, procedures/templates/procedure_main.html, procedures/tests_views.py, procedures/views.py
I added in a simple search bar to the patients and procedures index pages, after some team discussion I decided that adding the javascript improved searching is probably not worthwhile at this stage of the project.
=> Search models

SPP400/settings.py, assigned_procedures/admin.py, assigned_procedures/apps.py, assigned_procedures/models.py, assigned_procedures/tests.py, assigned_procedures/views.py, patients/models.py
This is the class for linking patients and procedures. It's essentially a join table with a many-to-many relationship with patients/procedures. Many of the methods in it are static as I can't think of any time you will need the AssignedProcedure object itself rather than some of the data associated with it.
Let me know if you have any questions because it's a little confusing
=> Patient procedure link

assigned_procedures/models.py, assigned_procedures/tests.py, procedures/models.py
Pretty simple pull request this time, just added the functions we needed to assign a roadmap to a patient. The way i have it set up, if we want to assign a modified roadmap it should be treated as an entirely new roadmap
=> Roadmap to patient backend

assigned_procedures/models.py, assigned_procedures/tests.py, homepage/static/homepage/login.css, homepage/templates/sidebar.html, patients/templates/patient.html, patients/templates/patient_procedures.html, patients/urls.py, patients/views.py, roadmaps/forms.py, roadmaps/models.py, roadmaps/templates/modify_roadmap.html, roadmaps/views.py
Roadmaps can be used to quickly assign common procedure flow to patients, and these procedures can also be removed from patients.
=> Add Roadmap to patient

assigned_procedures/tests_views.py, patients/tests_views.py, patients/views.py
Just more tests for adding/removing roadmaps from a patient
=> Add tests patient procedure

.travis.yml, assigned_procedures/tests_views.py, patients/templates/patient_procedures.html, patients/urls.py, patients/views.py
Users can now add procedure(s)-phase to a patient without the use of a roadmap.
=> Adding Individual procedure to patient

assigned_procedures/models.py, assigned_procedures/tests.py, patients/models.py, patients/tests.py
Added 2 new functionalities: the ability to update/check if a patient is behind a procedure goal, and the ability to retrieve a list of every patient who is behind.
=> Patient flagging

patients/forms.py, patients/templates/patient.html, patients/tests_forms.py, patients/tests_views.py, patients/urls.py, patients/views.py
Added flagging and unflagging on patient pages. Appreciate the help @Kyle-Levy 💯
=> Flag frontend

assigned_procedures/models.py, homepage/static/homepage/homepage.js, homepage/templates/homepage.html, homepage/views.py
Patient panels on the homepage for patients that have been flagged manually + system auto-flagged patients
=> Frontend alerts

assigned_procedures/tests_views.py, procedures/forms.py, procedures/models.py, procedures/templates/new_procedure.html, procedures/templates/procedure_main.html, procedures/templates/update_procedure.html, procedures/templates/view_procedure.html, procedures/tests_forms.py, procedures/tests_views.py, procedures/views.py, roadmaps/forms.py, roadmaps/models.py, roadmaps/templates/create_roadmap.html, roadmaps/templates/modify_roadmap.html, roadmaps/templates/roadmaps_main.html, roadmaps/templates/view_roadmap.html, roadmaps/tests_views.py, roadmaps/urls.py, roadmaps/views.py
integrated est_days_to_complete fields in all areas of roadmaps and procedures
=> Front-end time goals

.gitignore, SPP400/settings.py, analytics/admin.py, analytics/apps.py, analytics/models.py, analytics/tests.py, analytics/views.py, assigned_procedures/models.py, assigned_procedures/tests.py, homepage/views.py, requirements.txt
Created analytics app and database table. Also added method to calculate the % of procedures that are behind/return all behind assigned_procedures
I think the return method would better fit into the assigned_procedure class better than analytics but i think it's fine for now.
=> Percent finished

homepage/static/homepage/sidebar.css, patients/static/patients/patient.css, patients/templates/patient.html
Includes some changes to the patient's profile that made it a lot prettier. Was done in advance to have a nicer looking product for our meeting with Dr. Horwitz
=> Refactor patients page

SPP400/urls.py, analytics/models.py, assigned_procedures/forms.py, assigned_procedures/models.py, assigned_procedures/templates/assigned_procedure.html, assigned_procedures/tests.py, assigned_procedures/urls.py, assigned_procedures/views.py, patients/templates/patient.html, patients/views.py, roadmaps/templatetags/roadmap_extras.py
https://github.com/UIOWA5830SP19/SPP400/issues/153
This branch handles this issue, it is ready to be closed
=> Procedure status

assigned_procedures/forms.py, assigned_procedures/templates/assigned_procedure.html, assigned_procedures/views.py
Made changes to remove completion of procedures requested by @Kyle-Levy sorry no tests added in this pr will try to get to them soon
=> Form clean

assigned_procedures/models.py, assigned_procedures/tests.py, homepage/templates/homepage.html, patients/models.py, patients/static/patients/patient_profile.js, patients/templates/patient.html, patients/tests.py, patients/views.py
Homepage patient panels are finalized
- All three columns are displaying real data from the database (i.e referred patients show as referred, in-progress are actually in-progress)
-The patient's final procedures, next procedures, and today's procedures are shown in the appropriate places.
=> Finalize patient panels

assigned_procedures/models.py, assigned_procedures/tests.py, homepage/templates/homepage.html, patients/models.py, patients/templates/patient.html, patients/tests.py, patients/tests_models.py, patients/views.py
These commits were meant to be in the branch before it got merged.
=> Finalize patient panels 

procedures/templates/view_procedure.html, procedures/views.py
Displays all patients that have this procedure assigned to them on the view procedure page. Said patient name is a link to their profile.
=> Patients on procedure

assigned_procedures/models.py, assigned_procedures/tests.py, patients/models.py, patients/views.py, procedures/views.py
Patient's procedure-phase pairs must now be unique.
=> Unique procedure pair

analytics/models.py, analytics/tests_views.py, assigned_procedures/tests_views.py
covered remaining project files up to 90% with the exception of the roadmap extras template tag file
=> added test for analytics/views.py

homepage/templates/authenticate.html, homepage/templates/homepage.html, patients/templates/landing_page.html, procedures/templates/procedure_main.html, procedures/views.py, roadmaps/templates/roadmaps_main.html
just a couple style changes, moved buttons to the top of index pages to prevent endless scrolling
make sure to review everything closely as this will probably be one of the last changes
=> Grand finale
